const {chromium} = require(process.env.WD_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
  const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.WD_ATLAS_URL || 'http://127.0.0.1:8767/',{waitUntil:'domcontentloaded'});
  await page.waitForSelector('#wdLoading[hidden]',{state:'attached',timeout:60000});
  assert.equal(await page.locator('.mla-mast .mla-eyebrow').count(),0);
  await page.locator('#wdTabClimatology').click();
  await page.waitForSelector('#wdPathwayChartData tbody tr',{state:'attached'});
  assert.ok(await page.locator('#wdAnnualData tbody tr').count()>70);
  await page.locator('#wdAnnualMeasure').selectOption('rate');
  await page.locator('#wdTabExtremes').click();
  await page.waitForFunction(()=>document.querySelector('#wdScatterStatus').textContent.includes('with both values'));
  await page.locator('#wdScatter').scrollIntoViewIfNeeded();
  const hit=await page.evaluate(()=>{const a=WD_ATLAS,rows=a.filtered.map(i=>({i,x:a.extremeValue(i,'intensity'),y:a.extremeValue(i,'rain')})).filter(r=>Number.isFinite(r.x)&&Number.isFinite(r.y)),target=rows.reduce((best,r)=>r.y>best.y?r:best),xr=a.metricRange(rows.map(r=>r.x),false),yr=a.metricRange(rows.map(r=>r.y),false),box=document.querySelector('#wdScatter').getBoundingClientRect();return {index:target.i,x:box.left+65+(target.x-xr.minimum)/(xr.maximum-xr.minimum)*(box.width-85),y:box.top+20+(yr.maximum-target.y)/(yr.maximum-yr.minimum)*(box.height-70)};});
  await page.mouse.click(hit.x,hit.y);
  assert.equal(await page.evaluate(()=>WD_ATLAS.selected),hit.index);
  await page.locator('#wdTabExtremes').click();
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:path.join(process.env.WD_QA_DIR || '/tmp','wd-extremes-20260909.png'),fullPage:true});
  await page.locator('#wdScatterX').selectOption('diag:relative_humidity_500hpa_pct');
  await page.waitForFunction(()=>document.querySelector('#wdScatterStatus').textContent.includes('with both values'));
  await page.locator('#wdTabExplore').click();
  await page.locator('#wdPinReference').click();
  assert.equal(await page.locator('#wdClearReference').isVisible(),true);
  await page.evaluate(()=>{WD_ATLAS.state.months=new Set([1]);WD_ATLAS.applyFilters();});
  assert.ok((await page.locator('#wdProfileReadout').textContent()).includes('Reference:'));
  await page.waitForTimeout(400);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForSelector('#wdLoading[hidden]',{state:'attached',timeout:60000});
  assert.equal(await page.locator('#wdClearReference').isVisible(),true);
  assert.deepEqual(await page.evaluate(()=>[...WD_ATLAS.state.months]),[1]);
  await page.evaluate(()=>{WD_ATLAS.state.months=new Set([1,2,3,4,5,6,7,8,9,10,11,12]);WD_ATLAS.applyFilters();WD_ATLAS.selectTrack(16297,{fit:false});});
  const view=await page.evaluate(()=>JSON.stringify(WD_ATLAS.map.view));
  await page.evaluate(async()=>{const raw=await WD_ATLAS.fetchInflated('assets/wd-reanalysis-matches-v1.json.gz'),matches=JSON.parse(new TextDecoder().decode(raw));WD_ATLAS.selectTrack(WD_ATLAS.cat.id.indexOf(matches.sources.imdaa.matches[0].era5_track_id),{fit:false});});
  await page.locator('#wdReanalysis').selectOption('imdaa');
  await page.waitForFunction(()=>document.querySelector('#wdReanalysisStatus').textContent.includes('median separation'));
  assert.equal(await page.evaluate(()=>JSON.stringify(WD_ATLAS.map.view)),view);
  await page.evaluate(()=>WD_ATLAS.selectTrack(16297,{fit:false}));
  for(const mode of ['active','peakIntensity','peakPrecipitation']){
    await page.locator('#wdMonthMode').selectOption(mode,{force:true});
    assert.ok(await page.evaluate(()=>WD_ATLAS.filtered.every(i=>WD_ATLAS.trackMonths(i).some(m=>WD_ATLAS.state.months.has(m)))));
  }
  await page.locator('#wdMonthMode').selectOption('genesis',{force:true});
  if(process.env.WD_REQUIRE_COMPOSITES==='1'){
    await page.waitForFunction(()=>document.querySelector('#wdCompositeSelectedStatus').textContent.includes('snapshots;'),null,{timeout:60000});
    await page.locator('#wdCompositeVariable').selectOption('precipitation');
    await page.waitForFunction(()=>document.querySelector('#wdCompositeSelectedStatus').textContent.includes('UTC-day'));
    await page.locator('#wdCompositeVariable').selectOption('relative_vorticity');
    await page.waitForFunction(()=>document.querySelector('#wdCompositeSelectedStatus').textContent.includes('snapshots;'));
    await page.locator('#wdCompositeSelected').screenshot({path:path.join(process.env.WD_QA_DIR || '/tmp','wd-composite-selected.png')});
    await page.locator('#wdTabClimatology').click();
    await page.waitForFunction(()=>document.querySelector('#wdCompositeSubsetStatus').textContent.startsWith('Available fields:'),null,{timeout:90000});
    await page.locator('#wdCompositeSubset').evaluate(el=>el.scrollIntoView({block:'center'}));
    await page.locator('#wdCompositeSubset').screenshot({path:path.join(process.env.WD_QA_DIR || '/tmp','wd-composite-subset.png')});
  }
  if(process.env.WD_REQUIRE_CLIMATE==='1'){
    await page.locator('#wdTabClimateChange').click();
    await page.waitForFunction(()=>document.querySelector('#wdProjectionStatus').textContent.includes('paired models ·'),null,{timeout:60000});
    assert.ok(await page.locator('#wdProjectionData tbody tr').count()>3);
    await page.locator('#wdProjectionSeason').selectOption('jjas');
    await page.evaluate(()=>scrollTo(0,0));
    await page.screenshot({path:path.join(process.env.WD_QA_DIR || '/tmp','wd-climate-change.png'),fullPage:true});
  }
  await page.locator('#wdTabForecast').click();
  await page.waitForFunction(()=>document.querySelector('#wdForecastStatus').textContent.includes('member runs available'),null,{timeout:60000});
  await page.locator('#wdForecastLead').fill('48');
  await page.locator('#wdForecastLead').dispatchEvent('input');
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:path.join(process.env.WD_QA_DIR || '/tmp','wd-forecast-20260909.png'),fullPage:true});
  await page.locator('#wdForecastModel').selectOption('gefs');
  await page.waitForFunction(()=>document.querySelector('#wdForecastStatus').textContent.includes('31/31'),null,{timeout:90000});
  await page.locator('#wdForecastMembers').check();
  const member=await page.locator('#wdForecastSystem option').evaluateAll(options=>options.find(o=>o.value.includes(':c00-'))?.value);
  assert.ok(member);await page.locator('#wdForecastSystem').selectOption(member);
  assert.equal(await page.locator('#wdForecastSystem').inputValue(),member);
  await page.locator('#wdForecastEvolution').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#wdForecastLead').inputValue(),'54');
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('#wdLoading[hidden]',{state:'attached',timeout:60000});
  await page.waitForFunction(()=>document.querySelector('#wdForecastStatus').textContent.includes('31/31'),null,{timeout:90000});
  assert.equal(await page.locator('#wdForecastSystem').inputValue(),member);
  assert.equal(await page.locator('#wdForecastLead').inputValue(),'54');
  await page.locator('#wdForecastModel').selectOption('ifs');
  await page.waitForFunction(()=>document.querySelector('#wdForecastStatus').textContent.includes('1/1'),null,{timeout:60000});
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(300);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
  const ids=await page.locator('[id]').evaluateAll(nodes=>nodes.map(n=>n.id));assert.equal(new Set(ids).size,ids.length);
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
